test for reviews and reviews by id
jlinford84/BE--Project pull request #1
Opened 2022-10-10 14:45 UTC by jlinford84

2022-10-10 14:54 UTC, alexdevdavis requested changes
looking good so far, just need to add your 404 and 400 error handling tests and solution

2022-10-10 14:54 UTC, alexdevdavis commented on __tests__/app.test.js
> +          body.forEach((category) => {
when testing arrays, ensure to have an array length expect statement too, as forEach can otherwise easily create false positives

2022-10-10 14:54 UTC, alexdevdavis commented on __tests__/app.test.js
> +          body.forEach((category) => {
same applies as above

2022-10-10 14:54 UTC, alexdevdavis commented on controllers/reviews.controller.js
> +      console.log(err);
be sure to pass your err along to the error handling middleware I'm shortly going to ask you to write tests and solution for :)

2022-10-10 14:54 UTC, alexdevdavis commented on controllers/reviews.controller.js
> +    .catch((err) => {
as above, pass err to middleware

2022-10-11 10:02 UTC, HeatherEver approved these changes
Nice work Jon, just a minor change to make in your testing and a couple of console logs to get rid of! 
Lovely separate controllers and models, your code is looking very clean! 
No need to do another pull request. When these changes are done just merge away :)

2022-10-11 10:02 UTC, HeatherEver commented on __tests__/app.test.js
> +        expect(body.length !== 0)
this should be more specific - have a look how many categories there are and expect that many - otherwise we might only be getting 1 back and this would pass

2022-10-11 10:02 UTC, HeatherEver commented on __tests__/app.test.js
> +        expect(body.length !== 0)
same again!

2022-10-11 10:02 UTC, HeatherEver commented on __tests__/app.test.js
> +        expect(body.length !== 0)
here we're only expecting one

2022-10-11 10:02 UTC, HeatherEver commented on models/reviews.model.js
> +        console.log(rows, '<<<<<<<ROWS')
remove console logs

2022-10-11 10:02 UTC, HeatherEver commented on models/reviews.model.js
> +        console.log(review, '<<<<<<<REVIEW')
and again :)

2022-10-11 10:03 UTC, merged